source 'https://github.com/CocoaPods/Specs.git'

target 'SNColorPicker', :exclusive => true do
  pod "SNColorPicker", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SNColorPicker", :path => "../"

  
end
